spring:
  application:
    name: ticket-backend

  datasource:
    url: jdbc:postgresql://ep-sparkling-wildflower-ahrps1o8-pooler.c-3.us-east-1.aws.neon.tech/neondb
    username: neondb_owner
    password: ${PASSWORD_DATABASE}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    profiles:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: ${JWT_KEY}
  expiration: 7200000 # 2 horas
  refresh-token:
    expiration: 10800000 # 3 horas

server:
  port: 8080
  servlet:
    context-path: /api/v1


